name: Build on MacOS
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: true

    runs-on:
      - macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install ocaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.2.1

      - name: build
        run: |
          set -eux

          eval $(opam env)
          opam install --deps-only --with-test -y .
          make
          make test

          make -C standard
          ./standard/test_bin

      - name: upload compiler binary
        uses: actions/upload-artifact@v4
        with:
          name: austral-macos-bin
          path: austral
          retention-days: 14
